server:
  port: 8089

dubbo:
  application: # 应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
    name: robot_consumer # dubbo中的服务名称

  registry: # 注册中心配置，用于配置连接注册中心相关信息。
    address: zookeeper://127.0.0.1:2181 # zookeeper注册中心的地址

  protocol: # 协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
    name: dubbo  # dubbo的通讯协议名称
    port: -1 # 服务提供者端口2088x

  scan:
    base-packages: com.dedecms # dubbo的服务的扫描路径

  consumer:
    check: false


#  公钥和私钥 生成地址
#health:
#  jwt:
#    pubKeyPath: D:/keys/id_rsa.pub # 公钥地址
#    priKeyPath: D:/keys/id_rsa # 私钥地址
#    expire: 30 # 过期时间,单位分钟