spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dedecms_health?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


# dubbo配置
dubbo:
  protocol:
    name: dubbo # dubbo的通讯协议名称
    port: -1  # 服务提供者端口2088x

  registry:
    protocol: zookeeper  # zookeeper通讯协议的名称
    address: zookeeper://127.0.0.1:2181 # zookeeper注册中心的地址

  scan:
    base-packages: com.dedecms.health.service.impl # dubbo的服务的扫描路径

  provider:
    timeout: 30000 # 设置超时时间

  consumer:
    check: false # 设置是否检查服务存在，false不检查

logging:
  level:
    com:
      dedecms:
        health: info # 日志的输出级别